name: flutter_colorpicker
description: HSV(HSB)/HSL/RGB/Material color picker inspired by all the good design for your amazing flutter apps.
version: 1.0.3
homepage: https://github.com/mchome/flutter_colorpicker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
